### ISSUE TITLE
Simulation Runs but doesn't end. Blank output files generated when manually exiting.

### ISSUE THREAD

**Issue by TASKxMANAGER** [crond-jaist/GridAttackSim#2]
I've installed all the requirements for gridattacksim.
When I run python3 GridAttackSim.py It starts. I can select options and start the simulation.

I get the message that the simulation has started.
3 windows pop up (fcnc, ns-3, ?). The third window opens and closes shortly after. I think it's the subprocess to get the I'd of the running process and check it it ended.

The simulation never ends on its own. If I do end it by closing the popup Windows, it does generate csv files but they are blank. Do I have to input other data into the system? I do great blank csv files named "baseprice_clearedprice_clearedquantity.csv" and 'totalload.csv and put these in the folders in the appropriate database.

The files do show up when I press show results. Graphing them produces nothing because the files are empty. 

No other errors show. How long does simulation normally take? Or are there additional inputs I should provide? Shown Below is an image of what I see after simulation has started. The output files show up when I manually end the process. The process never ends on its own.
![Screen Shot 2022-04-05 at 3 06 27 PM](https://user-images.githubusercontent.com/94653871/161875715-6546d910-1f63-4518-aa39-50ded5ea418a.png)

**Comment by christobear** [comment]
I'm answering my own question. There's only two windows but looking at run.sh there's should be 3. The missing window is the gridlabd window. There are no explicit errors showing so I ran the code for the window on it's own. It was erroring and exiting without displaying any information.

The problem turned out to be FNCS dependencies missing.

**Comment by crond-jaist** [comment]
Hi,
I am glad you discovered the issue by yourself. Our software typically runs fine, but it depends on several tools, such as FNCS, which have their own dependencies, so usually the problems you may encounter are related to those other tools. 
In the future I suggest checking that the other tools run correctly by themselves in case of execution troubles. For the moment, since your problem seems solved, let me close this issue.
Best wishes,
Razvan
